# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-nginx-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-nginx-webserver
  template:
    metadata:
      labels:
        app: notes-nginx-webserver
    spec:
      containers:
        - name: notes-nginx-webserver
          image: jairjosafath/notes-nginx-webserver:latest
          ports:
            - containerPort: 80
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notes-nginx-webserver
spec:
  selector:
    app: notes-nginx-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
