apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # your username and password could be anything, but base64 encode them before adding to your yaml file
  username: YWN0aXgtYXBwCg== # echo actix-app | base64
  password: cGFzc3dvcmQxMjMK # echo password123 | base64
